export function explainDocument(text: string) {

  const lower = text.toLowerCase();

  let type = "General Document";
  let summary = "The document contains readable information.";
  let confidence = 60;

  // -----------------------
  // TYPE DETECTION
  // -----------------------

  if (
    lower.includes("electric") ||
    lower.includes("meter") ||
    lower.includes("units") ||
    lower.includes("consumer")
  ) {
    type = "Electricity / Utility Bill";
    summary = "This document appears to be an electricity bill.";
    confidence = 92;

  } else if (
    lower.includes("doctor") ||
    lower.includes("hospital") ||
    lower.includes("patient") ||
    lower.includes("clinic")
  ) {
    type = "Hospital / Medical Document";
    summary = "This document appears to be related to a hospital visit.";
    confidence = 90;

  } else if (
    lower.includes("legal") ||
    lower.includes("section") ||
    lower.includes("court") ||
    lower.includes("advocate")
  ) {
    type = "Legal Notice / Legal Document";
    summary = "This document appears to be a legal notice.";
    confidence = 88;

  } else if (
    lower.includes("invoice") ||
    lower.includes("receipt") ||
    lower.includes("gst") ||
    lower.includes("tax")
  ) {
    type = "Invoice / Payment Receipt";
    summary = "This document appears to be a payment invoice or receipt.";
    confidence = 85;
  }

  // -----------------------
  // AMOUNT EXTRACTION
  // -----------------------

  function extractTotalAmount(text: string) {
    const totalMatch = text.match(/total\s*(amount)?[:\s]*(₹|rs\.?)?\s?(\d+[.,]?\d*)/i);
    if (totalMatch) return "₹" + totalMatch[3];

    const all = [...text.matchAll(/(₹|rs\.?)\s?(\d+[.,]?\d*)/gi)];
    if (all.length > 0) return "₹" + all[all.length - 1][2];

    return null;
  }

  const amount = extractTotalAmount(text);

  // -----------------------
  // 🔥 NAME EXTRACTION (FINAL FIXED)
  // -----------------------

  function cleanName(name: string) {
    return name
      .replace(/gst|invoice|tax|bill|number|no\.?|rs|total/gi, "")
      .replace(/[0-9]/g, "")
      .replace(/[‘’"'`]/g, "")
      .replace(/\s{2,}/g, " ")
      .trim();
  }

  function fixName(name: string) {
    const words = name.split(" ").filter(w => w.length > 2);

    const unique = [...new Set(words)];

    return unique
      .slice(0, 2)
      .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
      .join(" ");
  }

  function extractName(text: string) {

    const lines = text.split("\n").map(l => l.trim()).filter(Boolean);

    for (let i = 0; i < lines.length; i++) {

      const line = lines[i].toLowerCase();

      if (line.includes("bill") && line.includes("to")) {

        for (let j = i + 1; j < i + 4 && j < lines.length; j++) {

          let candidate = lines[j];

          if (
            candidate.toLowerCase().includes("gst") ||
            candidate.toLowerCase().includes("invoice") ||
            candidate.toLowerCase().includes("tax") ||
            candidate.match(/\d/)
          ) continue;

          if (candidate.length > 3) {
            return fixName(cleanName(candidate));
          }
        }
      }
    }

    // fallback
    for (let line of lines) {

      if (
        line.toLowerCase().includes("gst") ||
        line.toLowerCase().includes("invoice") ||
        line.toLowerCase().includes("total") ||
        line.match(/\d{2,}/)
      ) continue;

      if (/^[A-Za-z]{3,}\s+[A-Za-z]{3,}/.test(line)) {
        return fixName(cleanName(line));
      }
    }

    return null;
  }

  const name = extractName(text);

  // -----------------------
  // OTHER EXTRACTION
  // -----------------------

  const date = text.match(/\d{1,2}[\/\-\s][A-Za-z0-9]{2,9}[\/\-\s]\d{2,4}/);

  const consumer = text.match(/consumer\s*(no|number)?[:\-]?\s*(\d+)/i);

  // -----------------------
  // RISK
  // -----------------------

  let risk = "Low";

  if (amount) {
    const num = parseInt(amount.replace(/[₹,]/g, ""));
    if (num > 50000) risk = "High";
    else if (num > 10000) risk = "Medium";
  }

  // -----------------------
  // 📄 FINAL SHAREABLE REPORT
  // -----------------------

  let result = `
📄 *Lexplain AI Report*

━━━━━━━━━━━━━━━

📌 *Document Type:* ${type}
🧠 *Confidence:* ${confidence}%

📑 *Summary:*  
${summary}

💰 *Total Amount:* ${amount || "Not detected"}

📊 *Details:*  
${name ? `👤 Name: ${name}\n` : ""}
${date ? `📅 Date: ${date[0]}\n` : ""}
${consumer ? `🔢 Consumer No: ${consumer[2]}\n` : ""}

━━━━━━━━━━━━━━━

📌 *Insight:*  
This document involves ${amount || "a"} transaction.

⚠️ *Risk Level:* ${risk}

📝 *Advice:*  
Verify details before payment.

━━━━━━━━━━━━━━━

🤖 Generated by Lexplain AI
`;

  return result;
}